### ISSUE TITLE
Capture Water Meter readouts

### ISSUE THREAD

**Issue by glenndierckx** [HouseOfTheFuture/TickTack#4]
We want to be able to capture the magnetic pulses of water meters to process them with software..

**Comment by glenndierckx** [comment]
Benny and I were able to capture pulses of 0.5 liter! You can see it in action here: https://instagram.com/p/6S--g1iV3F/

**Comment by BennyM** [comment]
As you can see the LED is most of the time on, perhaps we need to change the reed sensor from a normally open type to a normally closed one. Then again, we don't need to optimize at this stage.
